from . import log
from . import btf as btf_mod

NEEDED_STRUCTS = {
    "task_struct": [
        ("TASK_THREAD_INFO_FLAGS", "thread_info"),
        ("TASK_PID", "pid"),
        ("TASK_TGID", "tgid"),
        ("TASK_COMM", "comm"),
        ("TASK_TASKS", "tasks"),
        ("TASK_CRED", "cred"),
        ("TASK_REAL_CRED", "real_cred"),
        ("TASK_SECCOMP", "seccomp"),
        ("TASK_ATOMIC_FLAGS", "atomic_flags"),
        ("TASK_FILES", "files"),
        ("TASK_MM", "mm"),
        ("TASK_ACTIVE_MM", "active_mm"),
    ],
    "cred": [
        ("CRED_UID", "uid"),
        ("CRED_GID", "gid"),
        ("CRED_EUID", "euid"),
        ("CRED_EGID", "egid"),
        ("CRED_SUID", "suid"),
        ("CRED_SGID", "sgid"),
        ("CRED_FSUID", "fsuid"),
        ("CRED_FSGID", "fsgid"),
        ("CRED_CAPS", "cap_inheritable"),
        ("CRED_SECURITY", "security"),
        ("CRED_USER_NS", "user_ns"),
    ],
    "seccomp": [
        ("SECCOMP_MODE", "mode"),
        ("SECCOMP_FILTER_COUNT", "filter_count"),
        ("SECCOMP_FILTER", "filter"),
    ],
    "thread_info": [
        ("THREAD_INFO_FLAGS", "flags"),
    ],
    "pipe_buffer": [
        ("PIPE_BUFFER_PAGE", "page"),
        ("PIPE_BUFFER_OFFSET", "offset"),
        ("PIPE_BUFFER_LEN", "len"),
        ("PIPE_BUFFER_OPS", "ops"),
        ("PIPE_BUFFER_FLAGS", "flags"),
        ("PIPE_BUFFER_PRIVATE", "private"),
    ],
    "pipe_inode_info": [
        ("PIPE_HEAD", "head"),
        ("PIPE_TAIL", "tail"),
        ("PIPE_MAX_USAGE", "max_usage"),
        ("PIPE_RING_SIZE", "ring_size"),
        ("PIPE_NR_ACCOUNTED", "nr_accounted"),
        ("PIPE_READERS", "readers"),
        ("PIPE_WRITERS", "writers"),
        ("PIPE_FILES", "files"),
        ("PIPE_TMP_PAGE", "tmp_page"),
        ("PIPE_BUFS", "bufs"),
        ("PIPE_USER", "user"),
    ],
}

def export(btf, kernel_version=None, vermagic=None):
    lines = []
    lines.append("/* Auto-generated by kxray from BTF */")
    if kernel_version:
        lines.append(f"/* Kernel: {kernel_version} */")
    if vermagic:
        lines.append(f"/* Vermagic: {vermagic} */")
    lines.append("")
    lines.append("#ifndef OFFSETS_H")
    lines.append("#define OFFSETS_H")
    lines.append("")
    if kernel_version:
        lines.append(f"#define KXRAY_KERNEL_VERSION \"{kernel_version}\"")
    if vermagic:
        lines.append(f"#define KXRAY_VERMAGIC \"{vermagic}\"")
    if kernel_version or vermagic:
        lines.append("")
    for struct_name, fields in NEEDED_STRUCTS.items():
        s = btf_mod.find_struct(btf, struct_name)
        if not s:
            log.warn(f"struct {struct_name} not found")
            continue
        lines.append(f"/* {struct_name} (size=0x{s.size_or_type:X}) */")
        for macro, field in fields:
            m = btf_mod.find_field(s, field)
            if not m:
                log.warn(f"field {struct_name}.{field} not found")
                continue
            off = m.offset // 8
            lines.append(f"#define {macro}_OFF 0x{off:X}")
        lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)